# Generated by Django 4.0.3 on 2022-05-20 20:23

import calendar_app.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedField(model_container=calendar_app.models.Blog)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
